# Connessione al Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=xnyp12687474

# Configurazioni di Spring Data JPA e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Directory upload file
file.upload-dir=C:/gestionale_uploads

# Upload Limits
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Logging
logging.level.com.sac_gestionale=DEBUG